// <auto-generated />
using System;
using EtkinlikYonetim.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EtkinlikYonetim.Migrations
{
    [DbContext(typeof(EtkinlikYonetimContext))]
    [Migration("20220407171443_EtkinlikYonetimContextSnapshot")]
    partial class EtkinlikYonetimContextSnapshot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Turkish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EtkinlikYonetim.Models.EyEtkinlik", b =>
                {
                    b.Property<int>("EtkinlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("etkinlikID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BaslangicTarihi")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("baslangicTarihi");

                    b.Property<DateTime?>("BitisTarihi")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("bitisTarihi");

                    b.Property<string>("EtkinlikAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("etkinlikAdi");

                    b.Property<int?>("MaxKatilimciSayisi")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("maxKatilimciSayisi");

                    b.Property<DateTime?>("deleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EtkinlikId");

                    b.ToTable("EY_etkinlik");
                });

            modelBuilder.Entity("EtkinlikYonetim.Models.EyEtkinlikKullaniciEslesme", b =>
                {
                    b.Property<int>("EtkinlikKullaniciEslesmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("etkinlikKullaniciEslesmeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EtkinlikId")
                        .HasColumnType("int")
                        .HasColumnName("etkinlikId");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("kullaniciId");

                    b.Property<bool>("girisYapildi")
                        .HasColumnType("bit");

                    b.HasKey("EtkinlikKullaniciEslesmeId");

                    b.HasIndex("EtkinlikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EY_etkinlikKullaniciEslesme");
                });

            modelBuilder.Entity("EtkinlikYonetim.Models.EyKullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("kullaniciID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sifre");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("soyad");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .HasColumnName("tcNo")
                        .IsFixedLength(true);

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("telefonNo");

                    b.Property<string>("Yetki")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("yetki");

                    b.HasKey("KullaniciId");

                    b.HasIndex(new[] { "TcNo" }, "UQ__EY_kulla__E078675086B74C3F")
                        .IsUnique();

                    b.ToTable("EY_kullanici");
                });

            modelBuilder.Entity("EtkinlikYonetim.Models.EyEtkinlikKullaniciEslesme", b =>
                {
                    b.HasOne("EtkinlikYonetim.Models.EyEtkinlik", "Etkinlik")
                        .WithMany("EyEtkinlikKullaniciEslesmes")
                        .HasForeignKey("EtkinlikId")
                        .HasConstraintName("FK_EY_etkinlikKullaniciEslesme_EY_etkinlik")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EtkinlikYonetim.Models.EyKullanici", "Kullanici")
                        .WithMany("EyEtkinlikKullaniciEslesmes")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK_EY_etkinlikKullaniciEslesme_EY_kullanici")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Etkinlik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EtkinlikYonetim.Models.EyEtkinlik", b =>
                {
                    b.Navigation("EyEtkinlikKullaniciEslesmes");
                });

            modelBuilder.Entity("EtkinlikYonetim.Models.EyKullanici", b =>
                {
                    b.Navigation("EyEtkinlikKullaniciEslesmes");
                });
#pragma warning restore 612, 618
        }
    }
}
